magic_square: magic_square.c
	gcc -g magic_square.c -o magic_square

sorted_snackbar: sorted_snackbar.c
	gcc sorted_snackbar.c -o sorted_snackbar

match_braces: match_braces.c
	gcc -g match_braces.c -o match_braces

all: magic_square sorted_snackbar match_braces

clean:
	rm magic_square sorted_snackbar match_braces 3> /dev/null
